import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Replay - Pour ne jamais oublier les moments où Skander nous a dit qu'il allait 1v9",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <Head>
        <link href="https://vjs.zencdn.net/8.10.0/video-js.css" rel="stylesheet" />
        <script defer src="https://vjs.zencdn.net/8.10.0/video.min.js"></script>
      </Head>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </>
    );
}
